export type DosenEntry = {
  nip: string;
  nidn: string;
  kode: string;
  name: string;
  email: string;
  kkNama: string;
};

export const DOSEN_REFERENCE: DosenEntry[] = [
  { nip: "25000021", nidn: "", kode: "HEN", name: "A. Magfirah Nugraheni, S.Ds., M.Ds.", email: "amagfirahnugraheni@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "22890018", nidn: "0616098901", kode: "ADI", name: "Abednego Dwi Septiadi, S.Kom., M.Kom.", email: "abednego@telkomuniversity.ac.id", kkNama: "Software Engineering and Multimedia" },
  { nip: "14830059", nidn: "0601128301", kode: "ALD", name: "Achmad Rizal Danisya, S.T., M.T.", email: "achmadd@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "20910032", nidn: "0631089101", kode: "ACS", name: "Dr. Achmad Sultoni, S.Pd., M.Pd", email: "achmadsu@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "19870006", nidn: "0613118701", kode: "AZK", name: "Achmad Zaki Yamani, S.T., M.T.", email: "achmady@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "22930002", nidn: "0627089301", kode: "AWP", name: "Adanti Wido Paramadini, S.T., M.Eng", email: "adanti@telkomuniversity.ac.id", kkNama: "Bioengineering, Food Technology and Advance Material" },
  { nip: "23960028", nidn: "0622019601", kode: "AYR", name: "Ade Yanyan Ramdhani, S.T., M.T.", email: "yanyanramdhani@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "17930052", nidn: "0624119303", kode: "ADN", name: "Aditya Dwi Putro W., S.Kom., M.Kom.", email: "adityaw@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "22930043", nidn: "0607069302", kode: "ATI", name: "Aditya Tama Isdiarto, S.Sn., M.Sn.", email: "adityai@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "20890004", nidn: "0608118902", kode: "AWT", name: "Aditya Wijayanto, S.Kom., M.Sc.", email: "adityawi@telkomuniversity.ac.id", kkNama: "Cyber Security, IOT, and Cloud System" },
  { nip: "23880011", nidn: "0611118802", kode: "ANS", name: "Adnan Setyoko, S.Pd., M.Pd", email: "adnans@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "25980021", nidn: "", kode: "AFF", name: "Affan Hilmy Natsir, S.Kom., M.Eng.", email: "affanhilmynatsir@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "24940003", nidn: "0618069402", kode: "AFZ", name: "Affriza Brilyan Relo Pambudi Agus Putra, S.Kom., M.Kom.", email: "affrizabrilyan@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "25940039", nidn: "", kode: "URT", name: "Afin Muhammad Nurtsani, S.T., M.T.", email: "afinmuhammadn@telkomuniversity.ac.id", kkNama: "Bioengineering, Food Technology and Advance Material" },
  { nip: "24800001", nidn: "0727108006", kode: "ADM", name: "Agatha Dinarah Sri Rumestri, S.T., M.Ds.", email: "agathadinarah@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "20880003", nidn: "0617098802", kode: "AGI", name: "Agi Prasetiadi, S.T., M.Eng", email: "agiprasetiadi@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "23950028", nidn: "0614059501", kode: "AWS", name: "Agung Wicaksono, S.T., M.T", email: "agungwicaksonopwt@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "14820069", nidn: "0606118201", kode: "APT", name: "Agus Priyanto, S.Kom., M.Kom.", email: "aguspriyanto@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "24990007", nidn: "0629019901", kode: "ALR", name: "Aina Latifa Riyana Putri, S.Si., M.Mat.", email: "ainaqp@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "23940012", nidn: "0613109401", kode: "AYA", name: "Aiza Yudha Pratama, S.T., M.Sc", email: "aizayp@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "22940004", nidn: "0613079402", kode: "AJH", name: "Ajeng Dyah Kurniawati, S.T.P., M.Sc.", email: "ajengk@telkomuniversity.ac.id", kkNama: "Bioengineering, Food Technology and Advance Material" },
  { nip: "22980044", nidn: "0618059801", kode: "AJT", name: "Ajeng Tita Negoro, S.Pd., M.Sn.", email: "ajengn@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "25000020", nidn: "", kode: "HLD", name: "Alfilia Hilda Rahmatika, S.M., M.M., CPHRM., CHRBP", email: "alfiliahilda@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "03780042", nidn: "0621087801", kode: "AHM", name: "Dr. Alfin Hikmaturokhman, S.T., M.T.", email: "alfinh@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "20920001", nidn: "0606019201", kode: "ABX", name: "Amalia Beladinna Arifa, S.Pd., M.Cs", email: "amaliabela@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "23960005", nidn: "0610079602", kode: "AMS", name: "Aminatus Sa'adah, S.Si., M.Si.", email: "aminatuss@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "22910004", nidn: "0609049102", kode: "ANB", name: "Anastasia Febiyani, S.T., M.T", email: "anastasiaf@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "23930008", nidn: "0616129301", kode: "APV", name: "Andi Prademon Yunus, ST., M.Sc. Eng., Ph.D.", email: "andiay@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "25980018", nidn: "", kode: "AGW", name: "Angga Kurniawan, S.Pd., M.Kom.", email: "anggakurniawan@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "23870011", nidn: "0601128701", kode: "AIZ", name: "Anggi Zafia, S.T., M.Eng", email: "anggiz@telkomuniversity.ac.id", kkNama: "Cyber Security, IOT, and Cloud System" },
  { nip: "25990029", nidn: "", kode: "GGO", name: "Anggo Ahmad Saputra, S.Ds., M.Ds.", email: "anggoahmadsaputra@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "02780045", nidn: "0604097801", kode: "AGG", name: "Dr. Anggun Fitrian Isnawati, S.T., M.Eng.", email: "angguni@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "23940015", nidn: "0607079403", kode: "ANT", name: "Annisaa Utami, S.Kom., M.Cs.", email: "annisaau@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "24910002", nidn: "0604119101", kode: "ARB", name: "Arief Rais Bahtiar, S.Kom., M.Kom", email: "ariefbahtiar@telkomuniversity.ac.id", kkNama: "Software Engineering and Multimedia" },
  { nip: "17870120", nidn: "0611018702", kode: "AAH", name: "Arif Amrulloh, S.Kom., M.Kom", email: "arifta@telkomuniversity.ac.id", kkNama: "Software Engineering and Multimedia" },
  { nip: "24940005", nidn: "0611119403", kode: "AYD", name: "Arif Riyandi, S.Kom., M.Kom.", email: "arifriyandi@telkomuniversity.ac.id", kkNama: "Software Engineering and Multimedia" },
  { nip: "20870019", nidn: "0601098701", kode: "AWD", name: "Arif Wirawan Muhammad, S.Kom., M.Kom", email: "arifnm@telkomuniversity.ac.id", kkNama: "Cyber Security, IOT, and Cloud System" },
  { nip: "22930007", nidn: "0630069302", kode: "ACW", name: "Ariq Cahya Wardhana, S.Kom., M.Kom", email: "ariqcahya@telkomuniversity.ac.id", kkNama: "Software Engineering and Multimedia" },
  { nip: "22850004", nidn: "0621018503", kode: "APD", name: "Arsita Pinandita, S.Sn., M.Sn", email: "arsitap@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "19870003", nidn: "0603048702", kode: "AWM", name: "Aswan Munang, S.T., M.T.", email: "aswanm@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "18900103", nidn: "0625029002", kode: "ATF", name: "Dr. Atik Febriani, S.T., M.T.", email: "atikaf@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "23870004", nidn: "0615128703", kode: "ARI", name: "Atika Ratna Dewi, S.Si., M.Sc", email: "atikad@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "24890004", nidn: "0609128902", kode: "ADO", name: "Aulia Desy Nur Utomo, S.Kom., M.Cs", email: "auliau@telkomuniversity.ac.id", kkNama: "Cyber Security, IOT, and Cloud System" },
  { nip: "19820008", nidn: "0630058202", kode: "ABD", name: "Auliya Burhanuddin, S.Si., M.Kom.", email: "auliyaburhanuddin@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "24930007", nidn: "0607099302", kode: "BRB", name: "Bachrul Restu Bagja, S.Pd., M.Sn.", email: "bachrulb@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "25990037", nidn: "", kode: "BKS", name: "Bella Okta Sari Miranda, S.Kom., M.Kom", email: "bellaoktasarimiranda@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "18890122", nidn: "0603118901", kode: "BGA", name: "Bongga Arifwidodo, S.ST., M.T.", email: "bonggaa@telkomuniversity.ac.id", kkNama: "Cyber Security, IOT, and Cloud System" },
  { nip: "23900012", nidn: "0221019002", kode: "CPR", name: "Cahyo Prihantoro, S.Kom., M.Eng", email: "cahyop@telkomuniversity.ac.id", kkNama: "Cyber Security, IOT, and Cloud System" },
  { nip: "23960006", nidn: "0603089601", kode: "CMH", name: "Chusnul Maulidina Hidayat, S.M., M.M.", email: "chusnulh@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "18910100", nidn: "0602129101", kode: "CWA", name: "Citra Wiguna, S.Kom., M.Kom", email: "citraw@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "18900108", nidn: "0617049001", kode: "CKO", name: "Condro Kartiko, S.Kom., MTI.", email: "condrokartiko@telkomuniversity.ac.id", kkNama: "Software Engineering and Multimedia" },
  { nip: "14850077", nidn: "0626108502", kode: "DPI", name: "Dadiek Pranindito, S.T., M.T.", email: "dadiekp@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "22850005", nidn: "0620108501", kode: "DYX", name: "Daniel Yeri Kristiyanto, S.Kom., M.Kom., M.Si.", email: "danielk@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "13820029", nidn: "0619048201", kode: "DKN", name: "Danny Kurnianto, S.T., M.Eng", email: "dannykurnianto@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "23920011", nidn: "0620029202", kode: "DCA", name: "Dany Candra Febrianto, S.Kom., M.Eng.", email: "danycandra@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "23940013", nidn: "0626108502", kode: "DSA", name: "Dasril Aldo, S.Kom., M.Kom", email: "dasrilaldo@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "24850002", nidn: "0231108502", kode: "DAP", name: "Dedy Agung Prabowo, S.Kom., M.Kom", email: "dedyaprabowo@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "17930050", nidn: "5249771672230283", kode: "DHT", name: "Diah Septiani, S.Kom., M.C.S.(AI).", email: "diahseptiani@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "23930003", nidn: "0604059303", kode: "DKI", name: "Dian Kartika Sari, S.Si., M.Pd.", email: "dianks@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "22930041", nidn: "0618109301", kode: "DCF", name: "Dr. Diandra Chika Fransisca, S.Si., M.Sc.", email: "diandraf@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "13840016", nidn: "0618038404", kode: "DSP", name: "Dr. Didi Supriyadi, S.T., M.Kom.", email: "didisupriyadi@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "22920032", nidn: "0731039201", kode: "DFN", name: "Dimas Fanny Hebrasianto Permadi, S.ST., M.Kom.", email: "dimasfhp@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "22920008", nidn: "0615089201", kode: "DRY", name: "Ir. Dina Rachmawaty, S.T., M.T", email: "dinarr@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "22900009", nidn: "0610119002", kode: "DPR", name: "Diovianto Putra Rakhmadani, S.Kom., M.M", email: "diovianto@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "17870121", nidn: "0617078703", kode: "DZN", name: "Dodi Zulherman, S.T., M.T., PhD.", email: "zulherman@telkomuniversity.ac.id", kkNama: "Bioengineering, Food Technology and Advance Material" },
  { nip: "03780006", nidn: "0622017801", kode: "DJA", name: "Dwi Januarita Ardianing Kusuma, S.T., M.Kom", email: "dwijanuarita@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "18910116", nidn: "0617019102", kode: "DWA", name: "Dwi Mustika Kusumawardani, S.Kom., M.Kom.", email: "dwimustika@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "25950034", nidn: "", kode: "IAN", name: "Ega Adrianto, S.T., M.T.", email: "egaadriantoea@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "25880002", nidn: "0220058803", kode: "EKS", name: "Eka Sahputra, S.Kom., M.Kom.", email: "ekasahputra@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "14860011", nidn: "0629018602", kode: "ESN", name: "Eka Setia Nugraha, S.T., M.T.", email: "ekavon@telkomuniversity.ac.id", kkNama: "Bioengineering, Food Technology and Advance Material" },
  { nip: "05760048", nidn: "0617117601", kode: "EKW", name: "Eka Wahyudi, S.T., M.Eng.", email: "ekawahyudi@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "13870071", nidn: "0616098703", kode: "EFC", name: "Eko Fajar Cahyadi, S.T., M.T., Ph.D", email: "ekofajarcahyadi@telkomuniversity.ac.id", kkNama: "Cyber Security, IOT, and Cloud System" },
  { nip: "20910031", nidn: "0624079101", kode: "ELG", name: "Elianna Gerda Pertiwi, S.Sn., M.Sn", email: "eliannap@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "14870094", nidn: "0621128701", kode: "EII", name: "Emi Iryanti, S.ST., M.T.", email: "emikpi@telkomuniversity.ac.id", kkNama: "Software Engineering and Multimedia" },
  { nip: "23930016", nidn: "0613039301", kode: "EFZ", name: "Emmareta Fauziah, S.Ds., M.Ds", email: "emmaretaf@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "23920005", nidn: "0615059201", kode: "ENF", name: "Erlina Nur Arifani, S.T.P., M.Sc.", email: "erlinanurarifani@telkomuniversity.ac.id", kkNama: "Bioengineering, Food Technology and Advance Material" },
  { nip: "24970002", nidn: "0612069703", kode: "EZD", name: "Evia Zunita Dwi Pratiwi, S.T., M.Sc.", email: "eviazdp@telkomuniversity.ac.id", kkNama: "Bioengineering, Food Technology and Advance Material" },
  { nip: "18840116", nidn: "0622018403", kode: "FMW", name: "Fahrudin Mukti Wibowo, S.Kom., M.Eng.", email: "fahrudinw@telkomuniversity.ac.id", kkNama: "Cyber Security, IOT, and Cloud System" },
  { nip: "22930008", nidn: "0607079301", kode: "FDH", name: "Faisal Dharma Adhinata, S.Kom., M.Kom.", email: "faisaldharma@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "22920027", nidn: "0608129203", kode: "FZH", name: "Faizah, S.TP., M.Si.", email: "faizahfzh@telkomuniversity.ac.id", kkNama: "Bioengineering, Food Technology and Advance Material" },
  { nip: "22950015", nidn: "0601049501", kode: "FDN", name: "Famila Dwi Winati, S.T., M.Sc", email: "familaw@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "17900085", nidn: "0622039001", kode: "FKR", name: "Fauza Khair, S.T., M.Eng.", email: "fauzakhair@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "18900105", nidn: "0631039004", kode: "FZX", name: "Fauzan Romadlon, S.T.P., M. Eng.", email: "fauzanro@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "19880019", nidn: "0623058803", kode: "FDD", name: "Ferdinanda, M.Sn", email: "ferdinandavty@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "17870111", nidn: "0619028701", kode: "FTF", name: "Fikra Titan Syifa, S.T., M.Eng.", email: "fikras@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "23900013", nidn: "0605089003", kode: "GPP", name: "Galih Putra Pamungkas, S.Sn., M.Sn", email: "galihpp@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "26930001", nidn: "0402109301", kode: "GML", name: "Gayuh Minang Lati, S.T., M.B.A.", email: "gayuhminanglati@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "23860003", nidn: "0620058602", kode: "GRM", name: "Gilang Ramadhan, S.Sn., M.Ds", email: "gilangram@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "20930034", nidn: "0620039302", kode: "GFA", name: "Gita Fadila Fitriana, S.Kom., M.Kom", email: "gitafadila@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "23929013", nidn: "0610099201", kode: "GPU", name: "Gladi Pawestri Utami, S.Sn., M.Sn", email: "gladipawestri@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "15790041", nidn: "0627087901", kode: "WIB", name: "Gunawan Wibisono, S.T., M.T.", email: "gwibisono@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "13860001", nidn: "0601018601", kode: "GWS", name: "Gunawan Wibisono, S.Kom., M.Kom", email: "gunawanw@telkomuniversity.ac.id", kkNama: "Cyber Security, IOT, and Cloud System" },
  { nip: "24850001", nidn: "0618088504", kode: "GNL", name: "Gusnita Linda, S.Sn., M.Hum", email: "gusnital@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "22960015", nidn: "0601029601", kode: "HQK", name: "Halim Qista Karima, S.T., M.Sc", email: "halimk@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "23890002", nidn: "0604068901", kode: "HWU", name: "Hari Widi Utomo, S.Pd., M.Ed", email: "hariiu@telkomuniversity.ac.id", kkNama: "Software Engineering and Multimedia" },
  { nip: "25930039", nidn: "", kode: "TAT", name: "Henry Dwi Prihartanto, S.T., M.Eng.", email: "henrydwip@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "16880039", nidn: "0617068801", kode: "HPO", name: "Herryawan Pujiharsono, S.T., M.Eng.", email: "herryawanp@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "25920031", nidn: "", kode: "DIY", name: "Imam Adiyana, S.Stat., M.Si.", email: "imamadiyana@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "20930039", nidn: "0625079302", kode: "IPE", name: "Indah Permatasari, S.Si., M.Si", email: "indahpermata@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "17840104", nidn: "0614048403", kode: "IPA", name: "Ipam Fuaddina Adam, S.T., M.Kom.", email: "ipamya@telkomuniversity.ac.id", kkNama: "Cyber Security, IOT, and Cloud System" },
  { nip: "22890003", nidn: "0616068903", kode: "IQK", name: "Iqsyahiro Kresna A, S.T., M.T", email: "hiroka@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "22930009", nidn: "0610069301", kode: "IRX", name: "Irmayatul Hikmah, S.Si., M.Si", email: "irmayatulh@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "03660025", nidn: "0614086602", kode: "IST", name: "Dr. Irwan Susanto, S.T., M.M.", email: "irwans@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "13800011", nidn: "0603038002", kode: "JAN", name: "Jaenal Arifin, S.T., M.Eng.", email: "jaenala@telkomuniversity.ac.id", kkNama: "Bioengineering, Food Technology and Advance Material" },
  { nip: "20890003", nidn: "0620108901", kode: "JGG", name: "Jafaruddin Gusti Amri Ginting, S.T., M.T", email: "jafargustiamri@telkomuniversity.ac.id", kkNama: "Cyber Security, IOT, and Cloud System" },
  { nip: "25989003", nidn: "", kode: "KAR", name: "Karina Amanda Larasati, S.T, M.T", email: "karinaamandalarasati@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "22940009", nidn: "0618059401", kode: "KMN", name: "Khairun Nisa Meiah Ngafidin, S.Pd., M.Kom", email: "nisameiah@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "24930006", nidn: "0619129301", kode: "KNM", name: "Khoirun Ni'amah, S.T, M.T", email: "khoirunn@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "22860002", nidn: "", kode: "KHM", name: "Kholidiyah Masykuroh, S.T., M.T.", email: "kholidiyahma@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "13830037", nidn: "0606088303", kode: "KNO", name: "Kukuh Nugroho, S.T., M.T.", email: "kukuhn@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "25910001", nidn: "0318109102", kode: "UUA", name: "Kurnia Indah Sumunar, S.E., M.S.Ak", email: "kurniaindahsumunar@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "23940014", nidn: "0616109401", kode: "LWO", name: "Laurensius Windy Octanio Haryanto, S.Ds., M.Ds", email: "laurensiuswindy@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "22970040", nidn: "0620119701", kode: "LFL", name: "Lina Fatimah Lishobrina, S.A.B., M.M.", email: "linaflishobrina@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "24990008", nidn: "0608049901", kode: "LIX", name: "Lisda, S.Kom., M.Kom.", email: "lisdalis@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "25960037", nidn: "", kode: "LDH", name: "Lukman Adhitama", email: "lukmanadhitamala@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "22900010", nidn: "0609119002", kode: "LWH", name: "Luqman Wahyudi, S.Sn., M.Sn.", email: "luqmanw@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "25850001", nidn: "0507078501", kode: "NGH", name: "M. Agung Nugroho, S.Kom., M.Kom.", email: "magungnugroho@telkomuniversity.ac.id", kkNama: "Cyber Security, IOT, and Cloud System" },
  { nip: "20870021", nidn: "0630108704", kode: "LLO", name: "M. Lukman Leksono, S.Pd., M.Pd", email: "lukmanl@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "23900010", nidn: "0601099002", kode: "MYK", name: "M. Yoka Fathoni, S.Kom., M.Kom", email: "myokafathoni@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "23930009", nidn: "0624039305", kode: "MHF", name: "Mahazam Afrad, S.Kom., M.Kom", email: "mahazama@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "24990013", nidn: "0601059901", kode: "MIH", name: "Maie Istighosah, S.Kom., M.Kom.", email: "maieistigh@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "17930051", nidn: "0627099301", kode: "MPA", name: "Maliana Puspa Arum, S.E., M.M", email: "malianaa@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "23930011", nidn: "0627099303", kode: "MSA", name: "Maryona Septiara, S.Pd., M.Kom.", email: "septiara@telkomuniversity.ac.id", kkNama: "Software Engineering and Multimedia" },
  { nip: "22930010", nidn: "0617059302", kode: "MAF", name: "Mas Aly Afandi, S.ST., M.T", email: "alyafandi@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "22930011", nidn: "0611069301", kode: "MPT", name: "Mega Pranata, S.Pd., M.Kom", email: "mpranata@telkomuniversity.ac.id", kkNama: "Cyber Security, IOT, and Cloud System" },
  { nip: "22960062", nidn: "0622079601", kode: "MBG", name: "Melinda Br. Ginting, S.T., M.T.", email: "melindag@telkomuniversity.ac.id", kkNama: "Bioengineering, Food Technology and Advance Material" },
  { nip: "23720002", nidn: "0620077203", kode: "MTA", name: "Miftahol Arifin, S.T., M.T", email: "miftahola@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "25990036", nidn: "", kode: "MMM", name: "Muammar, S.Kom., M.Kom.", email: "muammarm@telkomuniversity.ac.id", kkNama: "Cyber Security, IOT, and Cloud System" },
  { nip: "23920003", nidn: "0625059201", kode: "MAW", name: "Muhamad Awiet Wiedanto Prasetyo, S.Kom., M.MSI.", email: "awietmwp@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "22930012", nidn: "0614089302", kode: "MAL", name: "Muhamad Azrino Gustalika, S.Kom., M.Tr.T", email: "azrino@telkomuniversity.ac.id", kkNama: "Software Engineering and Multimedia" },
  { nip: "22910006", nidn: "0630119104", kode: "MAT", name: "Muhammad Afrizal Amrustian, S.Kom., M.Kom", email: "muhammada@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "22920024", nidn: "0627069203", kode: "MEP", name: "Muhammad Eka Purbaya, S.T., M.Eng", email: "mekapur@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "18910098", nidn: "0619029102", kode: "MFI", name: "Muhammad Fajar Sidiq, S.T., M.T.", email: "mfsidiq@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "23970027", nidn: "0606019702", kode: "MIF", name: "Muhammad Iqbal Faturohman, S.T., M.B.A., M.Sc.", email: "iqbalfaturohman@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "23950030", nidn: "0421019501", kode: "MLU", name: "Muhammad Lulu Latif Usman, S.Pd., M.Han.", email: "muhlulu@telkomuniversity.ac.id", kkNama: "Software Engineering and Multimedia" },
  { nip: "22930013", nidn: "0625029301", kode: "PKP", name: "Muhammad Panji Kusuma Praja, S.T., M.T", email: "panjipraja@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "24960006", nidn: "0627119601", kode: "MRZ", name: "Muhammad Raafi'u Firmansyah, S.Kom., M.Eng", email: "raafiu@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "23890001", nidn: "0619048901", kode: "MYR", name: "Muhammad Yusro, S.T, M.Biotech.", email: "muhammadyusro@telkomuniversity.ac.id", kkNama: "Bioengineering, Food Technology and Advance Material" },
  { nip: "15880087", nidn: "0626128801", kode: "MZN", name: "Muhammad Zidny Naf'an, S.Kom., M.Kom.", email: "muhammadn@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "17900073", nidn: "0607129002", kode: "MAA", name: "Muntaqo Alfin Amanaf S.ST., M.T.", email: "muntaqoa@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "23920002", nidn: "0628119201", kode: "NNQ", name: "Nabila Noor Qisthani, S.T., M.T", email: "nabilaqisthani@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "24880003", nidn: "9990613676", kode: "NIS", name: "Nenen Isnaeni, S.Kom., M.Kom.", email: "nenisna@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "20920034", nidn: "0630049203", kode: "NAR", name: "Nia Annisa Ferani Tanjung, S.Si., M.Sc.", email: "niaannisa@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "24940004", nidn: "0605129401", kode: "NEW", name: "Nicolaus Euclides Wahyu Nugroho, S.Kom., M.Cs", email: "nicolausn@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "25010030", nidn: "", kode: "ERK", name: "Nisrina Hanifa Setiono, S.Kom., M.Cs.", email: "nisrinahanifas@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "19880002", nidn: "0628118902", kode: "NRZ", name: "Nofrizaldi S.Sn., M.Sn.", email: "nofrizaldinya@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "19900007", nidn: "0627119002", kode: "NAY", name: "Novanda Alim Setya Nugraha, S.S., M.Hum.", email: "novandan@telkomuniversity.ac.id", kkNama: "Software Engineering and Multimedia" },
  { nip: "23910005", nidn: "0609119103", kode: "NAP", name: "Novian Adi Prasetyo, S.Kom., M.Kom", email: "novian@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "23929010", nidn: "0627129201", kode: "NAH", name: "Nur Afifah Zen, S.Si., M.Si", email: "nurafifahzen@telkomuniversity.ac.id", kkNama: "Bioengineering, Food Technology and Advance Material" },
  { nip: "20880016", nidn: "0630098802", kode: "NUR", name: "Nurlaili, S.Pd., M.Pd.", email: "nurlaili@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "23960030", nidn: "0616029601", kode: "NLX", name: "Nurul Latifasari, S.TP., M.P.", email: "nurull@telkomuniversity.ac.id", kkNama: "Bioengineering, Food Technology and Advance Material" },
  { nip: "22950016", nidn: "0624059501", kode: "PRX", name: "Paradise, S.Kom., M.Kom", email: "paradise@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "23850012", nidn: "0620018502", kode: "PKG", name: "Petrus Kerowe Goran, S.T., M.T.", email: "petruskgoran@telkomuniversity.ac.id", kkNama: "Bioengineering, Food Technology and Advance Material" },
  { nip: "22940035", nidn: "0602079401", kode: "PAH", name: "Pradana Ananda Raharja, S.Kom., M.Kom", email: "pradanar@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "24940006", nidn: "0417019401", kode: "PHO", name: "Prasetyo Hartanto, S.E., M.M.", email: "prasetyohartanto@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "20920005", nidn: "0620079201", kode: "PYR", name: "Prasetyo Yuliantoro, S.T., M.T", email: "prasetyoy@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "24740001", nidn: "0704097402", kode: "PCT", name: "Dr. Pricilla Tamara, S.T., M.T.", email: "pricillai@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "20920032", nidn: "0631039201", kode: "RWX", name: "Rahmat Widadi, S.Pd, M.Eng.", email: "rahmat@telkomuniversity.ac.id", kkNama: "Bioengineering, Food Technology and Advance Material" },
  { nip: "25820002", nidn: "0706018203", kode: "MDI", name: "Rakhmad Maulidi, S.Kom., M.Kom.", email: "rakhmadmaulidi@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "23950004", nidn: "0609039502", kode: "RAI", name: "Ratih Alifah Putri, S.Ds., M.Ds.", email: "ratihp@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "24960009", nidn: "0626039602", kode: "RWA", name: "Ratih Windu Arini, S.T., M.T.", email: "ratiharini@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "26760001", nidn: "0307057601", kode: "RSY", name: "Resad Setyadi, S.T., S.Si., MMSI., Ph.D", email: "resads@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "22900011", nidn: "0626049003", kode: "RDO", name: "Ridho Ananda, S.Pd., M.Si", email: "ridhoa@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "15820053", nidn: "0625088202", kode: "RDN", name: "Dr. Ridwan Pandiya, S.Si., M.Sc.", email: "ridwanp@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "19910017", nidn: "0627089101", kode: "RAD", name: "Rifki Adhitama, S.Kom., M.Kom", email: "rifkiadhitama@telkomuniversity.ac.id", kkNama: "Software Engineering and Multimedia" },
  { nip: "23880002", nidn: "0613068802", kode: "RIS", name: "Riri Irma Suryani, S.Sn., M.Sn.", email: "ririgs@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "12780009", nidn: "0604027802", kode: "RFI", name: "Dr. Risa Farrid Christianti, S.T., M.T.", email: "risabc@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "25950040", nidn: "", kode: "SKI", name: "Risky Haryanto, S.T., M.Sc.", email: "riskyharyanto@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "12710047", nidn: "0609117101", kode: "RTN", name: "Riyatno, S.S., M.Hum.", email: "riyatnopurbowaseso@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "26920013", nidn: "", kode: "RZL", name: "Rizal Meifan, S.T., M.Eng", email: "rizalmeifan@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "25980029", nidn: "", kode: "RZM", name: "Rizki Amalia Pratiwi, S.Tr.T., M.T.", email: "rizkiamaliapratiwi@telkomuniversity.ac.id", kkNama: "Bioengineering, Food Technology and Advance Material" },
  { nip: "23860002", nidn: "0611068604", kode: "ROB", name: "Robert Hendra Yudianto, S.Sn., M.Sn", email: "roberty@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "22930014", nidn: "0604069301", kode: "RNI", name: "Rona Nisa Sofia Amriza, S.Kom., M.T.I., M.I.M", email: "ronanisa@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "24920005", nidn: "0201099202", kode: "SFR", name: "Sandhy Fernandez, S.Kom., M.Kom", email: "sandhyf@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "23890003", nidn: "0610108905", kode: "SAT", name: "Sarah Astiti, S.Kom., M.MT", email: "sarahas@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "25990024", nidn: "", kode: "GUM", name: "Satya Fajar Gumelar, S.M., MBA.", email: "satyafajarg@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "22920010", nidn: "0613109201", kode: "SWX", name: "Sena Wijayanto, S.Pd., M.T", email: "senawijayanto@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "22890017", nidn: "0626098903", kode: "SIP", name: "Sevia Indah Purnama, S.ST., M.T", email: "seviaindah@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "20840002", nidn: "0611068402", kode: "SRA", name: "Shinta Romadhona, S.T., M.T", email: "shintaromadhona@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "22920011", nidn: "0625069201", kode: "SDX", name: "Shintia Dwi Alika, S.Pd., M.Pd", email: "shintiaa@telkomuniversity.ac.id", kkNama: "Media, Design and Creative Innovation" },
  { nip: "13800026", nidn: "0622058005", kode: "SPR", name: "Sigit Pramono, S.T., M.T.", email: "sigitp@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "13910038", nidn: "0607119101", kode: "SVX", name: "Silvia Van Marsally, S.E., M.M.", email: "silviam@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "12870054", nidn: "0631078701", kode: "STX", name: "Sisilia Thya Safitri, S.T., M.T.", email: "sisiliathya@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "23810002", nidn: "0517108101", kode: "SIK", name: "Siti Khomsah, S.Kom., M.Cs", email: "sitijk@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "20880015", nidn: "0622028804", kode: "STI", name: "Slamet Indriyanto, S.T., M.T", email: "slamet@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "20930037", nidn: "0617069301", kode: "SLR", name: "Solichah Larasati, S.T, M.T", email: "solichahl@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "24930008", nidn: "0605049301", kode: "SDN", name: "Sudianto, S.Pd., M.Kom", email: "sudianto@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "23930012", nidn: "0629119302", kode: "SKD", name: "Sukmadiningtyas, S.Kom., M.Kom.", email: "sukmadiningtyasvxm@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "23900011", nidn: "0623079001", kode: "SHY", name: "Syarif Hidayatuloh, S.T., M.T", email: "syarif@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "15820023", nidn: "0605048201", kode: "SRF", name: "Syariful Ikhwan, S.T., M.T.", email: "syarifuli@telkomuniversity.ac.id", kkNama: "Cyber Security, IOT, and Cloud System" },
  { nip: "07820045", nidn: "0630068202", kode: "TWR", name: "Dr. Tenia Wahyuningrum, S.Kom., M.T.", email: "teniaw@telkomuniversity.ac.id", kkNama: "Software Engineering and Multimedia" },
  { nip: "23910004", nidn: "0613069102", kode: "TAA", name: "Toni Anwar, S.Kom., M.MSI", email: "tonianwar@telkomuniversity.ac.id", kkNama: "Software Engineering and Multimedia" },
  { nip: "22890004", nidn: "0602068902", kode: "THX", name: "Trihastuti Yuniati, S.Kom., M.T", email: "trihastutiy@telkomuniversity.ac.id", kkNama: "Cyber Security, IOT, and Cloud System" },
  { nip: "22900012", nidn: "0621129001", kode: "UMT", name: "Ummi Athiyah, S.Kom., M.Kom", email: "ummiathiyah@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "19910013", nidn: "0617029101", kode: "UMR", name: "Utti Marina Rifanti, S.Si., M.Sc.", email: "uttimarina@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "25010039", nidn: "", kode: "VIO", name: "Violita Anggraini, S.T., M.B.A., M.Sc.", email: "violitaanggraini@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "19850001", nidn: "0613038503", kode: "WAX", name: "Wahyu Adi Prabowo, S.Kom, M.B.A, M.Kom.", email: "wahyup@telkomuniversity.ac.id", kkNama: "Cyber Security, IOT, and Cloud System" },
  { nip: "20910009", nidn: "0628129101", kode: "WAA", name: "Wahyu Andi Saputra, S.Pd., M.Eng", email: "andiwahyu@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "02780016", nidn: "0606037801", kode: "WPS", name: "Dr. Wahyu Pamungkas, S.T., M.T.", email: "wahyupa@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "23850009", nidn: "0705108503", kode: "YDR", name: "Yesy Diah Rosita, S.Kom., M.Kom.", email: "yesydr@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "22870003", nidn: "0101088702", kode: "YDO", name: "Dr. Yogo Dwi Prasetyo, S.Si., M.Si", email: "yogoop@telkomuniversity.ac.id", kkNama: "Data Science and Optimization" },
  { nip: "23950029", nidn: "0627099501", kode: "YRF", name: "Yohani Setiya Rafika Nur, S.Kom., M.Kom", email: "yohanin@telkomuniversity.ac.id", kkNama: "Applied Artificial Intelligence" },
  { nip: "07780017", nidn: "0606037803", kode: "YDX", name: "Yosita Dwiani S, S.Pi., M.Si.", email: "yositad@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "22900013", nidn: "0615049005", kode: "YAK", name: "Yoso Adi Setyoko, S.T., M.T", email: "yosoms@telkomuniversity.ac.id", kkNama: "Cyber Security, IOT, and Cloud System" },
  { nip: "24000014", nidn: "0609020001", kode: "YIS", name: "Yudha Islami Sulistya, S.Kom., M.Cs", email: "yudhaislami@telkomuniversity.ac.id", kkNama: "Software Engineering and Multimedia" },
  { nip: "18890124", nidn: "0621128902", kode: "YUH", name: "Yudha Saintika, S.T., M.T.I.", email: "yudhas@telkomuniversity.ac.id", kkNama: "Information System, Digital Business & Data Driven Solution" },
  { nip: "17810001", nidn: "1012078103", kode: "YZM", name: "Yulian Zetta Maulana, S.T., M.T.", email: "yulianm@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
  { nip: "23930017", nidn: "0612069301", kode: "YUK", name: "Yulinda Uswatun Kasanah, S.T., M.Sc", email: "yulindakasanah@telkomuniversity.ac.id", kkNama: "Industrial Systems Engineering" },
  { nip: "17900074", nidn: "0604039001", kode: "ZHP", name: "Zein Hanni Pradana, S.T., M.T.", email: "zeinhp@telkomuniversity.ac.id", kkNama: "Electronics and Telecommunications Science" },
];
